// COMPLETE LEADFORM - ALL 30 FIELDS EXACTLY AS REQUIRED
// Copy this structure to: src/components/sales/LeadForm.jsx

import { useState } from "react";
import { useCreateLead } from "../../hooks/useLeads";
import useUIStore from "../../store/useUIStore";
import { useNavigate } from "react-router-dom";
import "./LeadForm.css";

const LeadForm = () => {
  const { mutate: createLead, isPending } = useCreateLead();
  const { showToast } = useUIStore();
  const navigate = useNavigate();

  // ALL 30 FIELDS - EXACT MAPPING
  const [form, setForm] = useState({
    // 1. SR.NO - Auto-generated by backend, don't include
    // 2. Sales Person - Auto-assigned to logged-in user, don't include
    
    visitDate: "",          // 3. VISIT DATE
    callingDate: "",        // 4. CALLING DATE
    followUpDate: "",       // 5. FOLLOW UP
    firmName: "",           // 6. Firm Name *REQUIRED*
    personName: "",         // 7. PERSON NAME *REQUIRED*
    designation: "",        // 8. designation
    mobileNo: "",           // 9. Mobile No. *REQUIRED*
    email: "",              // 10. email
    areaEstate: "",         // 11. Area estate
    address: "",            // 12. ADDRESS
    district: "",           // 13. district
    state: "",              // 14. state
    pincode: "",            // 15. pincode
    industry: "",           // 16. INDUSTRY
    segment: "",            // 17. Segment
    constitution: "",       // 18. constitution
    machine: "",            // 19. MACHINE
    remark: "",             // 20. REMARK
    bankName: "",           // 21. bank name
    visitType: "office",    // 22. VISIT - OFFICE/MEETING
    sanction: false,        // 23. sanction (checkbox)
    sanctionDate: "",       // 24. date (sanction date)
    amount: "",             // 25. amount
    meetingScheduled: false,// 26. meeting (checkbox)
    meetingDate: "",        // 27. date (meeting date)
    projectType: "loan",    // 28. SUPPLIER "LOAN/SUBSIDY"
    projectStatus: "",      // 29. project status
    ansClientType: "ans_client", // 30. ans client or other
  });

  const [errors, setErrors] = useState({});

  const validate = () => {
    const e = {};
    if (!form.firmName?.trim()) e.firmName = "Firm name required";
    if (!form.personName?.trim()) e.personName = "Person name required";
    if (!form.mobileNo?.trim()) e.mobileNo = "Mobile number required";
    return e;
  };

  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;
    setForm((prev) => ({
      ...prev,
      [name]: type === "checkbox" ? checked : value,
    }));
    setErrors((prev) => ({ ...prev, [name]: "" }));
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    const errs = validate();
    if (Object.keys(errs).length) {
      setErrors(errs);
      return;
    }

    createLead(form, {
      onSuccess: () => {
        showToast("Visit added successfully");
        navigate("/sales/leads");
      },
      onError: () => showToast("Failed to add visit", "error"),
    });
  };

  return (
    <form className="lead-form card" onSubmit={handleSubmit}>
      
      {/* SECTION 1: VISIT DATES */}
      <div className="lead-form__section">
        <div className="lead-form__section-icon">📅</div>
        <div>
          <div className="lead-form__section-title">Visit & Follow-up Dates</div>
          <div className="lead-form__section-desc">Track important timeline</div>
        </div>
      </div>

      <div className="lead-form__grid lead-form__grid--3">
        <div className="form-group">
          <label className="form-label">3. Visit Date</label>
          <input className="form-input" name="visitDate" type="date"
            value={form.visitDate} onChange={handleChange} />
        </div>
        <div className="form-group">
          <label className="form-label">4. Calling Date</label>
          <input className="form-input" name="callingDate" type="date"
            value={form.callingDate} onChange={handleChange} />
        </div>
        <div className="form-group">
          <label className="form-label">5. Follow Up Date</label>
          <input className="form-input" name="followUpDate" type="date"
            value={form.followUpDate} onChange={handleChange} />
        </div>
      </div>

      {/* SECTION 2: CLIENT DETAILS */}
      <div className="lead-form__section">
        <div className="lead-form__section-icon">🏢</div>
        <div>
          <div className="lead-form__section-title">Client Information</div>
          <div className="lead-form__section-desc">Firm and contact person details</div>
        </div>
      </div>

      <div className="lead-form__grid lead-form__grid--2">
        <div className="form-group">
          <label className="form-label">6. Firm Name *</label>
          <input className="form-input" name="firmName" value={form.firmName}
            onChange={handleChange} placeholder="ABC Industries Pvt Ltd" required />
          {errors.firmName && <span className="form-error">{errors.firmName}</span>}
        </div>
        <div className="form-group">
          <label className="form-label">7. Person Name *</label>
          <input className="form-input" name="personName" value={form.personName}
            onChange={handleChange} placeholder="Rajesh Kumar" required />
          {errors.personName && <span className="form-error">{errors.personName}</span>}
        </div>
      </div>

      <div className="lead-form__grid lead-form__grid--3">
        <div className="form-group">
          <label className="form-label">8. Designation</label>
          <input className="form-input" name="designation" value={form.designation}
            onChange={handleChange} placeholder="Managing Director" />
        </div>
        <div className="form-group">
          <label className="form-label">9. Mobile No. *</label>
          <input className="form-input" name="mobileNo" value={form.mobileNo}
            onChange={handleChange} placeholder="+91 98765 43210" required />
          {errors.mobileNo && <span className="form-error">{errors.mobileNo}</span>}
        </div>
        <div className="form-group">
          <label className="form-label">10. Email</label>
          <input className="form-input" name="email" type="email" value={form.email}
            onChange={handleChange} placeholder="contact@company.com" />
        </div>
      </div>

      {/* SECTION 3: ADDRESS */}
      <div className="lead-form__section">
        <div className="lead-form__section-icon">📍</div>
        <div>
          <div className="lead-form__section-title">Address Details</div>
        </div>
      </div>

      <div className="form-group">
        <label className="form-label">11. Area / Estate</label>
        <input className="form-input" name="areaEstate" value={form.areaEstate}
          onChange={handleChange} placeholder="GIDC Phase 2" />
      </div>

      <div className="form-group">
        <label className="form-label">12. Full Address</label>
        <textarea className="form-textarea" name="address" value={form.address}
          onChange={handleChange} placeholder="Plot No. 45, Sector 8..." />
      </div>

      <div className="lead-form__grid lead-form__grid--3">
        <div className="form-group">
          <label className="form-label">13. District</label>
          <input className="form-input" name="district" value={form.district}
            onChange={handleChange} />
        </div>
        <div className="form-group">
          <label className="form-label">14. State</label>
          <input className="form-input" name="state" value={form.state}
            onChange={handleChange} />
        </div>
        <div className="form-group">
          <label className="form-label">15. Pincode</label>
          <input className="form-input" name="pincode" value={form.pincode}
            onChange={handleChange} />
        </div>
      </div>

      {/* SECTION 4: BUSINESS INFO */}
      <div className="lead-form__section">
        <div className="lead-form__section-icon">💼</div>
        <div>
          <div className="lead-form__section-title">Business Information</div>
        </div>
      </div>

      <div className="lead-form__grid lead-form__grid--3">
        <div className="form-group">
          <label className="form-label">16. Industry</label>
          <input className="form-input" name="industry" value={form.industry}
            onChange={handleChange} placeholder="Manufacturing" />
        </div>
        <div className="form-group">
          <label className="form-label">17. Segment</label>
          <input className="form-input" name="segment" value={form.segment}
            onChange={handleChange} />
        </div>
        <div className="form-group">
          <label className="form-label">18. Constitution</label>
          <input className="form-input" name="constitution" value={form.constitution}
            onChange={handleChange} placeholder="Partnership / Pvt Ltd" />
        </div>
      </div>

      <div className="form-group">
        <label className="form-label">19. Machine</label>
        <input className="form-input" name="machine" value={form.machine}
          onChange={handleChange} />
      </div>

      <div className="form-group">
        <label className="form-label">20. Remark</label>
        <textarea className="form-textarea" name="remark" value={form.remark}
          onChange={handleChange} placeholder="Any additional notes..." />
      </div>

      {/* SECTION 5: BANKING & VISIT */}
      <div className="lead-form__section">
        <div className="lead-form__section-icon">🏦</div>
        <div>
          <div className="lead-form__section-title">Banking & Visit Details</div>
        </div>
      </div>

      <div className="lead-form__grid lead-form__grid--2">
        <div className="form-group">
          <label className="form-label">21. Bank Name</label>
          <input className="form-input" name="bankName" value={form.bankName}
            onChange={handleChange} placeholder="State Bank of India" />
        </div>
        <div className="form-group">
          <label className="form-label">22. Visit Type</label>
          <select className="form-select" name="visitType" value={form.visitType}
            onChange={handleChange}>
            <option value="office">Office Visit</option>
            <option value="meeting">Meeting</option>
          </select>
        </div>
      </div>

      {/* SANCTION DETAILS */}
      <div className="lead-form__grid lead-form__grid--3">
        <div className="form-group">
          <label className="form-checkbox">
            <input type="checkbox" name="sanction" checked={form.sanction}
              onChange={handleChange} />
            <span>23. Sanctioned</span>
          </label>
        </div>
        <div className="form-group">
          <label className="form-label">24. Sanction Date</label>
          <input className="form-input" name="sanctionDate" type="date"
            value={form.sanctionDate} onChange={handleChange} />
        </div>
        <div className="form-group">
          <label className="form-label">25. Amount (₹)</label>
          <input className="form-input" name="amount" type="number"
            value={form.amount} onChange={handleChange} placeholder="0" />
        </div>
      </div>

      {/* MEETING DETAILS */}
      <div className="lead-form__grid lead-form__grid--2">
        <div className="form-group">
          <label className="form-checkbox">
            <input type="checkbox" name="meetingScheduled"
              checked={form.meetingScheduled} onChange={handleChange} />
            <span>26. Meeting Scheduled</span>
          </label>
        </div>
        <div className="form-group">
          <label className="form-label">27. Meeting Date</label>
          <input className="form-input" name="meetingDate" type="date"
            value={form.meetingDate} onChange={handleChange} />
        </div>
      </div>

      {/* PROJECT DETAILS */}
      <div className="lead-form__grid lead-form__grid--3">
        <div className="form-group">
          <label className="form-label">28. Project Type (Loan/Subsidy)</label>
          <select className="form-select" name="projectType" value={form.projectType}
            onChange={handleChange}>
            <option value="loan">Loan</option>
            <option value="subsidy">Subsidy</option>
          </select>
        </div>
        <div className="form-group">
          <label className="form-label">29. Project Status</label>
          <input className="form-input" name="projectStatus" value={form.projectStatus}
            onChange={handleChange} placeholder="In Progress / Approved" />
        </div>
        <div className="form-group">
          <label className="form-label">30. ANS Client Type</label>
          <select className="form-select" name="ansClientType"
            value={form.ansClientType} onChange={handleChange}>
            <option value="ans_client">ANS Client</option>
            <option value="other">Other</option>
          </select>
        </div>
      </div>

      {/* FOOTER */}
      <div className="lead-form__footer">
        <button type="button" className="btn btn--ghost"
          onClick={() => navigate("/sales/leads")}>
          Cancel
        </button>
        <button type="submit" className="btn btn--primary" disabled={isPending}>
          {isPending ? "Saving..." : "Add Visit"}
        </button>
      </div>
    </form>
  );
};

export default LeadForm;